import jwt, { type JwtPayload } from 'jsonwebtoken';
import { env } from '$env/dynamic/private';

const DEVELOPMENT_JWT_SECRET = 'development-secret-key';
const NODE_ENV = env.NODE_ENV || process.env.NODE_ENV || 'development';
const JWT_EXPIRES_IN = env.JWT_EXPIRES_IN || process.env.JWT_EXPIRES_IN || '7d';
const DEFAULT_JWT_SECRETS = new Set([
	'development-secret-key',
	'your-super-secret-jwt-key-change-this-in-production'
]);

function getJwtSecret(): string {
	const secret = (env.JWT_SECRET || process.env.JWT_SECRET || '').trim();
	if (!secret) {
		if (NODE_ENV === 'production') {
			throw new Error('JWT_SECRET is required in production');
		}

		// Keep local development stable even when env vars are missing.
		return DEVELOPMENT_JWT_SECRET;
	}

	if (NODE_ENV === 'production') {
		if (secret.length < 32) {
			throw new Error('JWT_SECRET must be at least 32 characters in production');
		}

		if (DEFAULT_JWT_SECRETS.has(secret)) {
			throw new Error('JWT_SECRET must not use a default value in production');
		}
	}

	return secret;
}

const JWT_SECRET = getJwtSecret();

export interface JWTPayload {
	userCode: string;
	email: string;
	iat?: number;
	exp?: number;
}

/**
 * Generate JWT token
 */
export function generateToken(payload: Omit<JWTPayload, 'iat' | 'exp'>): string {
	return jwt.sign(payload, JWT_SECRET, {
		algorithm: 'HS256',
		expiresIn: JWT_EXPIRES_IN as string | number
	} as jwt.SignOptions);
}

/**
 * Verify and decode JWT token
 */
export function verifyToken(token: string): JWTPayload | null {
	try {
		const decoded = jwt.verify(token, JWT_SECRET, { algorithms: ['HS256'] });
		if (!decoded || typeof decoded !== 'object') {
			return null;
		}

		const payload = decoded as JwtPayload;
		if (typeof payload.userCode !== 'string' || typeof payload.email !== 'string') {
			return null;
		}

		return {
			userCode: payload.userCode,
			email: payload.email,
			iat: payload.iat,
			exp: payload.exp
		};
	} catch (error) {
		console.error('JWT verification failed:', error);
		return null;
	}
}

/**
 * Decode token expiration without signature verification.
 * Use only for tokens generated by this server in the same request.
 */
export function decodeTokenExpiration(token: string): number | null {
	const decoded = jwt.decode(token);
	if (!decoded || typeof decoded !== 'object' || typeof decoded.exp !== 'number') {
		return null;
	}
	return decoded.exp * 1000;
}
