/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
	[x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AcademicCycles {
	base_cost: Generated<Numeric>;
	branch_code: string;
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	end_date: Timestamp;
	is_active: Generated<boolean>;
	modality: string;
	notes: string | null;
	start_date: Timestamp;
	title: string;
	turn_1_attendance_time: string | null;
	turn_1_tolerance_minutes: Generated<number>;
	turn_2_attendance_time: string | null;
	turn_2_tolerance_minutes: Generated<number>;
	updated_at: Generated<Timestamp>;
}

export interface AcademicDegrees {
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	is_active: Generated<boolean>;
	name: string;
	short_name: string | null;
	sort_order: Generated<number>;
	updated_at: Generated<Timestamp>;
}

export interface AttendanceOverview {
	attendance_code: string | null;
	attendance_created_at: Timestamp | null;
	attendance_date: Timestamp | null;
	attendance_entry_time: string | null;
	attendance_observation: string | null;
	attendance_state: string | null;
	attendance_updated_at: Timestamp | null;
	branch_code: string | null;
	branch_name: string | null;
	cycle_code: string | null;
	cycle_degree_code: string | null;
	cycle_title: string | null;
	degree_code: string | null;
	degree_name: string | null;
	enrollment_code: string | null;
	enrollment_number: string | null;
	group_code: string | null;
	modality: string | null;
	roll_code: string | null;
	student_code: string | null;
	student_dni: string | null;
	student_full_name: string | null;
	student_number: string | null;
	student_phone: string | null;
	student_photo_url: string | null;
	turn: string | null;
}

export interface Attendances {
	attendance_date: Generated<Timestamp>;
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	enrollment_code: string;
	entry_time: string | null;
	observation: string | null;
	state: Generated<string>;
	updated_at: Generated<Timestamp>;
}

export interface AuthLoginRateLimits {
	blocked_until: Timestamp;
	failed_count: Generated<number>;
	first_attempt_at: Timestamp;
	rate_key: string;
	updated_at: Generated<Timestamp>;
}

export interface Branches {
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	name: string;
	state: boolean;
	users: string[];
}

export interface CashboxDailySummary {
	branch_code: string | null;
	branch_name: string | null;
	business_date: Timestamp | null;
	cashbox_day_code: string | null;
	cashier_full_name: string | null;
	cashier_user_code: string | null;
	closed_at: Timestamp | null;
	closed_by_user_code: string | null;
	closing_amount: Numeric | null;
	created_at: Timestamp | null;
	current_amount: Numeric | null;
	expense_amount: Numeric | null;
	income_amount: Numeric | null;
	notes: string | null;
	opened_by_user_code: string | null;
	opening_amount: Numeric | null;
	surrender_amount: Numeric | null;
	updated_at: Timestamp | null;
}

export interface CashboxDays {
	branch_code: string;
	business_date: Timestamp;
	cashier_user_code: string;
	closed_at: Timestamp | null;
	closed_by_user_code: string | null;
	closing_amount: Numeric | null;
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	notes: string | null;
	opened_by_user_code: string | null;
	opening_amount: Generated<Numeric>;
	updated_at: Generated<Timestamp>;
}

export interface CashboxMovements {
	amount: Numeric;
	branch_code: string;
	business_date: Timestamp;
	cashier_user_code: string;
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	direction: string;
	movement_type: string;
	note: string | null;
	registered_by_user_code: string;
	reversed_at: Timestamp | null;
	reversed_by_user_code: string | null;
	source_code: string;
	source_type: string;
	status: Generated<string>;
	updated_at: Generated<Timestamp>;
}

export interface CashOutflowOverview {
	amount: Numeric | null;
	branch_code: string | null;
	branch_name: string | null;
	cashier_full_name: string | null;
	cashier_user_code: string | null;
	code: string | null;
	concept: string | null;
	created_at: Timestamp | null;
	deleted_at: Timestamp | null;
	deleted_by_user_code: string | null;
	description: string | null;
	outflow_date: Timestamp | null;
	outflow_number: string | null;
	outflow_type: string | null;
	pending_amount: Numeric | null;
	registered_by_full_name: string | null;
	registered_by_user_code: string | null;
	responsible_name: string | null;
	returned_amount: Numeric | null;
	status: string | null;
	updated_at: Timestamp | null;
}

export interface CashOutflows {
	amount: Numeric;
	branch_code: string;
	cashier_user_code: string;
	code: Generated<string>;
	concept: string;
	created_at: Generated<Timestamp>;
	deleted_at: Timestamp | null;
	deleted_by_user_code: string | null;
	description: string | null;
	outflow_date: Generated<Timestamp>;
	outflow_number: Generated<string>;
	outflow_type: Generated<string>;
	registered_by_user_code: string;
	responsible_name: string | null;
	return_note: string | null;
	returned_amount: Generated<Numeric>;
	returned_at: Timestamp | null;
	returned_by_name: string | null;
	returned_by_user_code: string | null;
	status: Generated<string>;
	updated_at: Generated<Timestamp>;
}

export interface Courses {
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	name: string;
	updated_at: Generated<Timestamp>;
}

export interface CycleDegreeOverview {
	base_cost: Numeric | null;
	branch_code: string | null;
	branch_name: string | null;
	code: string | null;
	created_at: Timestamp | null;
	cycle_code: string | null;
	cycle_is_active: boolean | null;
	cycle_title: string | null;
	degree_code: string | null;
	degree_name: string | null;
	degree_short_name: string | null;
	degree_sort_order: number | null;
	end_date: Timestamp | null;
	label: string | null;
	modality: string | null;
	start_date: Timestamp | null;
	updated_at: Timestamp | null;
}

export interface CycleDegrees {
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	cycle_code: string;
	degree_code: string;
	updated_at: Generated<Timestamp>;
}

export interface CycleOverview {
	active_enrollment_count: number | null;
	base_cost: Numeric | null;
	branch_code: string | null;
	branch_name: string | null;
	code: string | null;
	created_at: Timestamp | null;
	degree_count: number | null;
	degrees_summary: string | null;
	end_date: Timestamp | null;
	enrollment_count: number | null;
	is_active: boolean | null;
	modality: string | null;
	notes: string | null;
	start_date: Timestamp | null;
	title: string | null;
	turn_1_attendance_time: string | null;
	turn_1_tolerance_minutes: number | null;
	turn_2_attendance_time: string | null;
	turn_2_tolerance_minutes: number | null;
	updated_at: Timestamp | null;
}

export interface DashboardCoursePerformanceTrend {
	average_score: Numeric | null;
	course_code: string | null;
	created_at: Timestamp | null;
	cycle_degree_code: string | null;
	eval_code: string | null;
	eval_date: Timestamp | null;
	eval_name: string | null;
	group_code: string | null;
}

export interface DashboardEnrollmentsByCycle {
	branch_code: string | null;
	cycle_code: string | null;
	cycle_title: string | null;
	enrollment_count: number | null;
	start_date: Timestamp | null;
}

export interface DashboardGeneralPerformanceTrend {
	average_score: Numeric | null;
	created_at: Timestamp | null;
	cycle_degree_code: string | null;
	eval_code: string | null;
	eval_date: Timestamp | null;
	eval_name: string | null;
	group_code: string | null;
}

export interface DashboardRecentBranchStudents {
	branch_code: string | null;
	created_at: Timestamp | null;
	cycle_title: string | null;
	degree_name: string | null;
	full_name: string | null;
	group_code: string | null;
	student_code: string | null;
	student_number: string | null;
}

export interface DashboardStudentScoreRanking {
	average_score: Numeric | null;
	cycle_degree_code: string | null;
	group_code: string | null;
	roll_code: string | null;
	student_code: string | null;
	student_full_name: string | null;
	total_evaluations: number | null;
}

export interface DriveFiles {
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	deleted_at: Timestamp | null;
	mime_type: string | null;
	name: string;
	parent_code: string | null;
	scope: Generated<string>;
	size: Generated<Int8>;
	storage_path: string | null;
	tag: string | null;
	type: Generated<string>;
	updated_at: Generated<Timestamp>;
	user_code: string;
}

export interface EnrollmentOverview {
	branch_code: string | null;
	branch_name: string | null;
	code: string | null;
	created_at: Timestamp | null;
	cycle_code: string | null;
	cycle_degree_code: string | null;
	cycle_title: string | null;
	degree_code: string | null;
	degree_name: string | null;
	end_date: Timestamp | null;
	enrollment_number: string | null;
	first_name: string | null;
	group_code: string | null;
	is_active: boolean | null;
	last_name: string | null;
	modality: string | null;
	observation: string | null;
	pay_cost: Numeric | null;
	roll_code: string | null;
	start_date: Timestamp | null;
	status: string | null;
	student_code: string | null;
	student_dni: string | null;
	student_full_name: string | null;
	student_number: string | null;
	student_phone: string | null;
	turn: string | null;
	updated_at: Timestamp | null;
}

export interface Enrollments {
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	cycle_degree_code: string;
	enrollment_number: Generated<string>;
	group_code: Generated<string>;
	is_active: Generated<boolean>;
	observation: string | null;
	pay_cost: Generated<Numeric>;
	roll_code: string;
	student_code: string;
	turn: Generated<string>;
	updated_at: Generated<Timestamp>;
}

export interface EvalAnswers {
	code: Generated<string>;
	enrollment_code: string;
	question_code: string;
	student_answer: string | null;
}

export interface EvalOverview {
	branch_code: string | null;
	branch_name: string | null;
	code: string | null;
	configured_question_count: number | null;
	created_at: Timestamp | null;
	cycle_code: string | null;
	cycle_degree_code: string | null;
	cycle_title: string | null;
	degree_code: string | null;
	degree_name: string | null;
	degree_short_name: string | null;
	degree_sort_order: number | null;
	eval_date: Timestamp | null;
	eval_sections: Json | null;
	group_code: string | null;
	has_questions: boolean | null;
	modality: string | null;
	name: string | null;
	planned_question_count: number | null;
	section_count: number | null;
	updated_at: Timestamp | null;
	user_code: string | null;
}

export interface EvalQuestions {
	code: Generated<string>;
	correct_key: string;
	eval_code: string;
	omitable: Generated<boolean>;
	order_in_eval: number;
	score_percent: Generated<Numeric>;
	section_code: string;
}

export interface EvalResults {
	blank_count: Generated<number>;
	calculated_at: Generated<Timestamp>;
	code: Generated<string>;
	correct_count: Generated<number>;
	enrollment_code: string;
	eval_code: string;
	incorrect_count: Generated<number>;
	score: Generated<Numeric>;
	section_code: string | null;
}

export interface Evals {
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	cycle_degree_code: string;
	eval_date: Timestamp;
	group_code: string;
	name: string;
	updated_at: Generated<Timestamp>;
	user_code: string;
}

export interface EvalSections {
	code: Generated<string>;
	course_code: string;
	eval_code: string;
	order_in_eval: number;
	question_count: number;
}

export interface Migrations {
	batch: number;
	executed_at: Generated<Timestamp>;
	id: string;
	name: string;
}

export interface PaymentItems {
	amount: Numeric;
	code: Generated<string>;
	concept_code: string;
	concept_label: string;
	created_at: Generated<Timestamp>;
	detail: string | null;
	payment_code: string;
	position: number;
	updated_at: Generated<Timestamp>;
}

export interface PaymentOverview {
	branch_code: string | null;
	branch_name: string | null;
	cashier_full_name: string | null;
	cashier_user_code: string | null;
	code: string | null;
	concept_summary: string | null;
	created_at: Timestamp | null;
	item_count: number | null;
	observation: string | null;
	payer_full_name: string | null;
	payment_date: Timestamp | null;
	payment_number: string | null;
	registered_by_full_name: string | null;
	registered_by_user_code: string | null;
	status: string | null;
	student_code: string | null;
	student_full_name: string | null;
	student_number: string | null;
	total_amount: Numeric | null;
	updated_at: Timestamp | null;
	voided_at: Timestamp | null;
	voided_by_user_code: string | null;
}

export interface Payments {
	branch_code: string;
	cashier_user_code: string;
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	observation: string | null;
	payer_full_name: string;
	payment_date: Generated<Timestamp>;
	payment_number: Generated<string>;
	registered_by_user_code: string;
	status: Generated<string>;
	student_code: string | null;
	total_amount: Generated<Numeric>;
	updated_at: Generated<Timestamp>;
	voided_at: Timestamp | null;
	voided_by_user_code: string | null;
}

export interface Permissions {
	action: string;
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	entity: string;
	user_code: string;
}

export interface StudentDriveLinks {
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	file_code: string;
	linked_by_user_code: string;
	student_code: string;
}

export interface StudentOverview {
	address: string | null;
	birth_date: Timestamp | null;
	code: string | null;
	created_at: Timestamp | null;
	current_branch_name: string | null;
	current_cycle_title: string | null;
	current_degree_name: string | null;
	current_enrollment_number: string | null;
	current_enrollment_status: string | null;
	dni: string | null;
	enrollments_count: number | null;
	first_name: string | null;
	full_name: string | null;
	last_name: string | null;
	observation: string | null;
	phone: string | null;
	photo_url: string | null;
	student_number: string | null;
	updated_at: Timestamp | null;
}

export interface Students {
	address: string | null;
	birth_date: Timestamp | null;
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	dni: string | null;
	first_name: string;
	last_name: string;
	observation: string | null;
	password_hash: string;
	phone: string | null;
	photo_url: string | null;
	student_number: Generated<string>;
	updated_at: Generated<Timestamp>;
}

export interface TeacherAttendanceOverview {
	attendance_code: string | null;
	attendance_created_at: Timestamp | null;
	attendance_date: Timestamp | null;
	attendance_entry_time: string | null;
	attendance_observation: string | null;
	attendance_state: string | null;
	attendance_updated_at: Timestamp | null;
	branch_code: string | null;
	branch_name: string | null;
	first_name: string | null;
	last_name: string | null;
	schedule_code: string | null;
	schedule_entry_time: string | null;
	schedule_tolerance_minutes: number | null;
	schedule_weekday: number | null;
	teacher_code: string | null;
	teacher_full_name: string | null;
	teacher_number: string | null;
	teacher_phone: string | null;
}

export interface TeacherAttendances {
	attendance_date: Generated<Timestamp>;
	branch_code: string;
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	entry_time: string;
	observation: string | null;
	schedule_code: string;
	state: string;
	teacher_code: string;
	updated_at: Generated<Timestamp>;
}

export interface TeacherOverview {
	code: string | null;
	created_at: Timestamp | null;
	first_name: string | null;
	full_name: string | null;
	last_name: string | null;
	phone: string | null;
	teacher_number: string | null;
	updated_at: Timestamp | null;
}

export interface Teachers {
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	first_name: string;
	last_name: string;
	phone: string | null;
	teacher_number: Generated<string>;
	updated_at: Generated<Timestamp>;
}

export interface TeacherSchedules {
	branch_code: string;
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	entry_time: string;
	teacher_code: string;
	tolerance_minutes: Generated<number>;
	updated_at: Generated<Timestamp>;
	weekday: number;
}

export interface Users {
	code: Generated<string>;
	created_at: Generated<Timestamp>;
	email: string;
	is_super_admin: Generated<boolean>;
	last_login: Timestamp | null;
	last_name: string | null;
	name: string | null;
	password_hash: string;
	photo_url: string | null;
	updated_at: Generated<Timestamp>;
}

export interface DB {
	academic_cycles: AcademicCycles;
	academic_degrees: AcademicDegrees;
	attendance_overview: AttendanceOverview;
	attendances: Attendances;
	auth_login_rate_limits: AuthLoginRateLimits;
	branches: Branches;
	cash_outflow_overview: CashOutflowOverview;
	cash_outflows: CashOutflows;
	cashbox_daily_summary: CashboxDailySummary;
	cashbox_days: CashboxDays;
	cashbox_movements: CashboxMovements;
	courses: Courses;
	cycle_degree_overview: CycleDegreeOverview;
	cycle_degrees: CycleDegrees;
	cycle_overview: CycleOverview;
	dashboard_course_performance_trend: DashboardCoursePerformanceTrend;
	dashboard_enrollments_by_cycle: DashboardEnrollmentsByCycle;
	dashboard_general_performance_trend: DashboardGeneralPerformanceTrend;
	dashboard_recent_branch_students: DashboardRecentBranchStudents;
	dashboard_student_score_ranking: DashboardStudentScoreRanking;
	drive_files: DriveFiles;
	enrollment_overview: EnrollmentOverview;
	enrollments: Enrollments;
	eval_answers: EvalAnswers;
	eval_overview: EvalOverview;
	eval_questions: EvalQuestions;
	eval_results: EvalResults;
	eval_sections: EvalSections;
	evals: Evals;
	migrations: Migrations;
	payment_items: PaymentItems;
	payment_overview: PaymentOverview;
	payments: Payments;
	permissions: Permissions;
	student_drive_links: StudentDriveLinks;
	student_overview: StudentOverview;
	students: Students;
	teacher_attendance_overview: TeacherAttendanceOverview;
	teacher_attendances: TeacherAttendances;
	teacher_overview: TeacherOverview;
	teacher_schedules: TeacherSchedules;
	teachers: Teachers;
	users: Users;
}
